import { readFile } from 'fs/promises';
import { resolve } from 'path';
import { config } from 'dotenv';
import { RagManager } from './rag/RagManager.js';
import { CodeReviewer } from './review/CodeReviewer.js';
import type { ReviewResult } from './review/CodeReviewer.js';

config();

function parseArgs(): { diffPath: string; repoPath: string } {
  const args = process.argv.slice(2);
  let diffPath = '';
  let repoPath = '.';

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--diff' && args[i + 1]) diffPath = args[++i];
    if (args[i] === '--repo' && args[i + 1]) repoPath = args[++i];
  }

  if (!diffPath) {
    console.error('Error: --diff <path> is required');
    process.exit(1);
  }

  return { diffPath, repoPath };
}

function formatReview(result: ReviewResult): string {
  const lines: string[] = ['# Code Review\n'];

  lines.push('## 🐛 Potential Bugs');
  if (result.bugs.length === 0) {
    lines.push('No potential bugs found.\n');
  } else {
    result.bugs.forEach((b) => lines.push(`- ${b}`));
    lines.push('');
  }

  lines.push('## 🏗️ Architectural Issues');
  if (result.architectural_issues.length === 0) {
    lines.push('No architectural issues found.\n');
  } else {
    result.architectural_issues.forEach((a) => lines.push(`- ${a}`));
    lines.push('');
  }

  lines.push('## 💡 Recommendations');
  if (result.recommendations.length === 0) {
    lines.push('No recommendations.\n');
  } else {
    result.recommendations.forEach((r) => lines.push(`- ${r}`));
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by AI Code Review Bot*');

  return lines.join('\n');
}

async function postGithubComment(body: string): Promise<void> {
  const token = process.env.GITHUB_TOKEN;
  const prNumber = process.env.PR_NUMBER;
  const repo = process.env.GITHUB_REPOSITORY;

  if (!token || !prNumber || !repo) return;

  const url = `https://api.github.com/repos/${repo}/issues/${prNumber}/comments`;
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      Accept: 'application/vnd.github+json',
    },
    body: JSON.stringify({ body }),
  });

  if (!response.ok) {
    const text = await response.text();
    console.warn(`[review-cli] Failed to post GitHub comment: ${response.status} ${text}`);
  } else {
    console.log('[review-cli] Posted review comment to PR');
  }
}

async function main(): Promise<void> {
  const { diffPath, repoPath } = parseArgs();

  const diff = await readFile(resolve(diffPath), 'utf-8');

  if (!diff.trim()) {
    console.log('No changes detected, skipping review.');
    process.exit(0);
  }

  const ragManager = new RagManager({
    sourcePath: resolve(repoPath, 'for_rag/project-docs'),
    outputPath: resolve(repoPath, 'rag-data'),
    embeddingModel: 'nomic-embed-text',
    ollamaUrl: process.env.OLLAMA_URL ?? 'http://localhost:11434',
    topK: 6,
    chunkSize: 500,
    chunkOverlap: 100,
  });

  const model = process.env.REVIEW_MODEL ?? 'openai/gpt-4o-mini';
  const reviewer = new CodeReviewer(ragManager, model);

  console.log('[review-cli] Running code review...');
  const result = await reviewer.review(diff, resolve(repoPath));

  const markdown = formatReview(result);
  console.log('\n' + markdown);

  await postGithubComment(markdown);
}

main().catch((err) => {
  console.error('[review-cli] Fatal error:', err instanceof Error ? err.message : err);
  process.exit(1);
});
